# Generated by Django 5.0.5 on 2024-05-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0005_userprofile_delete_user_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="donation",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mileage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
