# Generated by Django 5.0.5 on 2024-05-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0007_post_address_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("men", "MEN"), ("women", "WOMEN")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="mood",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="season",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="tpo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
