# Generated by Django 5.0.5 on 2024-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0008_post_gender_post_height_post_mood_post_season_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentedClothing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clothing_item", models.CharField(max_length=100)),
                ("rental_date", models.DateField()),
                ("return_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rented_clothings",
            field=models.ManyToManyField(blank=True, to="sharecloth.rentedclothing"),
        ),
    ]
