# Generated by Django 5.0.5 on 2024-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0009_rentedclothing_userprofile_rented_clothings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rented_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
