# Generated by Django 5.0.5 on 2024-06-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0010_userprofile_rent_date_userprofile_rented_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="rented_clothings",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="rent_date",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="rented_item",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="return_date",
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sharecloth.post",
                    ),
                ),
                (
                    "userprofile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sharecloth.userprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RentedClothing",
        ),
    ]
