# Generated by Django 5.0.5 on 2024-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0013_alter_post_tpo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="season",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spring", "봄"),
                    ("summer", "여름"),
                    ("autumn", "가을"),
                    ("winter", "겨울"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
