# Generated by Django 5.0.5 on 2024-06-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0014_alter_post_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("men", "남자"), ("women", "여자")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("street", "스트릿"),
                    ("casual", "캐주얼"),
                    ("minimal", "미니멀"),
                    ("amekaji", "아메카지"),
                    ("feminine", "페미닌"),
                    ("business", "비즈니스"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
