# Generated by Django 5.0.5 on 2024-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharecloth", "0015_alter_post_gender_alter_post_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tpo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("campus", "캠퍼스"),
                    ("date", "데이트"),
                    ("wedding", "하객룩(웨딩룩)"),
                    ("daily", "데일리"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
